// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: maclink.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ─── Envelope ────────────────────────────────────────────────────────────────
/// Every message sent over the WebSocket is wrapped in an Envelope.
public struct MLEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// UUID v4
  public var id: String = String()

  /// Unix ms
  public var timestamp: Int64 = 0

  public var payload: MLEnvelope.OneOf_Payload? = nil

  public var handshake: MLHandshake {
    get {
      if case .handshake(let v)? = payload {return v}
      return MLHandshake()
    }
    set {payload = .handshake(newValue)}
  }

  public var handshakeAck: MLHandshakeAck {
    get {
      if case .handshakeAck(let v)? = payload {return v}
      return MLHandshakeAck()
    }
    set {payload = .handshakeAck(newValue)}
  }

  public var notification: MLNotification {
    get {
      if case .notification(let v)? = payload {return v}
      return MLNotification()
    }
    set {payload = .notification(newValue)}
  }

  public var notificationAction: MLNotificationAction {
    get {
      if case .notificationAction(let v)? = payload {return v}
      return MLNotificationAction()
    }
    set {payload = .notificationAction(newValue)}
  }

  public var callEvent: MLCallEvent {
    get {
      if case .callEvent(let v)? = payload {return v}
      return MLCallEvent()
    }
    set {payload = .callEvent(newValue)}
  }

  public var audioOffer: MLAudioOffer {
    get {
      if case .audioOffer(let v)? = payload {return v}
      return MLAudioOffer()
    }
    set {payload = .audioOffer(newValue)}
  }

  public var audioAnswer: MLAudioAnswer {
    get {
      if case .audioAnswer(let v)? = payload {return v}
      return MLAudioAnswer()
    }
    set {payload = .audioAnswer(newValue)}
  }

  public var iceCandidate: MLIceCandidate {
    get {
      if case .iceCandidate(let v)? = payload {return v}
      return MLIceCandidate()
    }
    set {payload = .iceCandidate(newValue)}
  }

  public var heartbeat: MLHeartbeat {
    get {
      if case .heartbeat(let v)? = payload {return v}
      return MLHeartbeat()
    }
    set {payload = .heartbeat(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case handshake(MLHandshake)
    case handshakeAck(MLHandshakeAck)
    case notification(MLNotification)
    case notificationAction(MLNotificationAction)
    case callEvent(MLCallEvent)
    case audioOffer(MLAudioOffer)
    case audioAnswer(MLAudioAnswer)
    case iceCandidate(MLIceCandidate)
    case heartbeat(MLHeartbeat)

  }

  public init() {}
}

/// ─── Handshake ────────────────────────────────────────────────────────────────
public struct MLHandshake: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceName: String = String()

  /// persistent UUID
  public var deviceID: String = String()

  /// protocol version "1.0"
  public var version: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct MLHandshakeAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  public var macName: String = String()

  public var macID: String = String()

  /// only if accepted=false
  public var rejectReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ─── Notifications ────────────────────────────────────────────────────────────
public struct MLNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notificationKey: String = String()

  public var packageName: String = String()

  public var appName: String = String()

  public var title: String = String()

  public var text: String = String()

  public var subText: String = String()

  /// small app icon, compressed PNG
  public var iconPng: Data = Data()

  public var postedAt: Int64 = 0

  public var actions: [MLNotificationAction] = []

  public var isOngoing: Bool = false

  public var groupKey: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct MLNotificationAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notificationKey: String = String()

  public var actionKey: String = String()

  public var label: String = String()

  /// filled when action is a reply
  public var replyText: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ─── Calls ────────────────────────────────────────────────────────────────────
public struct MLCallEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var callID: String = String()

  public var state: MLCallEvent.State = .incoming

  public var callerName: String = String()

  public var callerNumber: String = String()

  public var callerPhotoPng: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case incoming // = 0
    case accepted // = 1
    case rejected // = 2
    case ended // = 3
    case outgoing // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .incoming
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .incoming
      case 1: self = .accepted
      case 2: self = .rejected
      case 3: self = .ended
      case 4: self = .outgoing
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .incoming: return 0
      case .accepted: return 1
      case .rejected: return 2
      case .ended: return 3
      case .outgoing: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [MLCallEvent.State] = [
      .incoming,
      .accepted,
      .rejected,
      .ended,
      .outgoing,
    ]

  }

  public init() {}
}

/// ─── WebRTC signaling ─────────────────────────────────────────────────────────
public struct MLAudioOffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var callID: String = String()

  public var sdp: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct MLAudioAnswer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var callID: String = String()

  public var sdp: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct MLIceCandidate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var callID: String = String()

  public var candidate: String = String()

  public var sdpMid: String = String()

  public var sdpMlineIndex: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ─── Heartbeat ────────────────────────────────────────────────────────────────
public struct MLHeartbeat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sentAt: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "maclink"

extension MLEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}timestamp\0\u{2}\u{8}handshake\0\u{3}handshake_ack\0\u{2}\u{9}notification\0\u{3}notification_action\0\u{4}\u{9}call_event\0\u{4}\u{a}audio_offer\0\u{3}audio_answer\0\u{3}ice_candidate\0\u{2}\u{8}heartbeat\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 10: try {
        var v: MLHandshake?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .handshake(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .handshake(v)
        }
      }()
      case 11: try {
        var v: MLHandshakeAck?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .handshakeAck(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .handshakeAck(v)
        }
      }()
      case 20: try {
        var v: MLNotification?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .notification(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .notification(v)
        }
      }()
      case 21: try {
        var v: MLNotificationAction?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .notificationAction(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .notificationAction(v)
        }
      }()
      case 30: try {
        var v: MLCallEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .callEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .callEvent(v)
        }
      }()
      case 40: try {
        var v: MLAudioOffer?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .audioOffer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .audioOffer(v)
        }
      }()
      case 41: try {
        var v: MLAudioAnswer?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .audioAnswer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .audioAnswer(v)
        }
      }()
      case 42: try {
        var v: MLIceCandidate?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .iceCandidate(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .iceCandidate(v)
        }
      }()
      case 50: try {
        var v: MLHeartbeat?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .heartbeat(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .heartbeat(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 2)
    }
    switch self.payload {
    case .handshake?: try {
      guard case .handshake(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .handshakeAck?: try {
      guard case .handshakeAck(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .notification?: try {
      guard case .notification(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .notificationAction?: try {
      guard case .notificationAction(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case .callEvent?: try {
      guard case .callEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
    }()
    case .audioOffer?: try {
      guard case .audioOffer(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
    }()
    case .audioAnswer?: try {
      guard case .audioAnswer(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 41)
    }()
    case .iceCandidate?: try {
      guard case .iceCandidate(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 42)
    }()
    case .heartbeat?: try {
      guard case .heartbeat(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 50)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLEnvelope, rhs: MLEnvelope) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLHandshake: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Handshake"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_name\0\u{3}device_id\0\u{1}version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceName, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLHandshake, rhs: MLHandshake) -> Bool {
    if lhs.deviceName != rhs.deviceName {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLHandshakeAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandshakeAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}mac_name\0\u{3}mac_id\0\u{3}reject_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.macName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.macID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.macName.isEmpty {
      try visitor.visitSingularStringField(value: self.macName, fieldNumber: 2)
    }
    if !self.macID.isEmpty {
      try visitor.visitSingularStringField(value: self.macID, fieldNumber: 3)
    }
    if !self.rejectReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectReason, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLHandshakeAck, rhs: MLHandshakeAck) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.macName != rhs.macName {return false}
    if lhs.macID != rhs.macID {return false}
    if lhs.rejectReason != rhs.rejectReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Notification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}notification_key\0\u{3}package_name\0\u{3}app_name\0\u{1}title\0\u{1}text\0\u{3}sub_text\0\u{3}icon_png\0\u{3}posted_at\0\u{1}actions\0\u{3}is_ongoing\0\u{3}group_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.notificationKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.appName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.subText) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.iconPng) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.postedAt) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.actions) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.isOngoing) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.groupKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.notificationKey.isEmpty {
      try visitor.visitSingularStringField(value: self.notificationKey, fieldNumber: 1)
    }
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 2)
    }
    if !self.appName.isEmpty {
      try visitor.visitSingularStringField(value: self.appName, fieldNumber: 3)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 4)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 5)
    }
    if !self.subText.isEmpty {
      try visitor.visitSingularStringField(value: self.subText, fieldNumber: 6)
    }
    if !self.iconPng.isEmpty {
      try visitor.visitSingularBytesField(value: self.iconPng, fieldNumber: 7)
    }
    if self.postedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.postedAt, fieldNumber: 8)
    }
    if !self.actions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.actions, fieldNumber: 9)
    }
    if self.isOngoing != false {
      try visitor.visitSingularBoolField(value: self.isOngoing, fieldNumber: 10)
    }
    if !self.groupKey.isEmpty {
      try visitor.visitSingularStringField(value: self.groupKey, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLNotification, rhs: MLNotification) -> Bool {
    if lhs.notificationKey != rhs.notificationKey {return false}
    if lhs.packageName != rhs.packageName {return false}
    if lhs.appName != rhs.appName {return false}
    if lhs.title != rhs.title {return false}
    if lhs.text != rhs.text {return false}
    if lhs.subText != rhs.subText {return false}
    if lhs.iconPng != rhs.iconPng {return false}
    if lhs.postedAt != rhs.postedAt {return false}
    if lhs.actions != rhs.actions {return false}
    if lhs.isOngoing != rhs.isOngoing {return false}
    if lhs.groupKey != rhs.groupKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLNotificationAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationAction"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}notification_key\0\u{3}action_key\0\u{1}label\0\u{3}reply_text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.notificationKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.actionKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.replyText) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.notificationKey.isEmpty {
      try visitor.visitSingularStringField(value: self.notificationKey, fieldNumber: 1)
    }
    if !self.actionKey.isEmpty {
      try visitor.visitSingularStringField(value: self.actionKey, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    if !self.replyText.isEmpty {
      try visitor.visitSingularStringField(value: self.replyText, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLNotificationAction, rhs: MLNotificationAction) -> Bool {
    if lhs.notificationKey != rhs.notificationKey {return false}
    if lhs.actionKey != rhs.actionKey {return false}
    if lhs.label != rhs.label {return false}
    if lhs.replyText != rhs.replyText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLCallEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CallEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}call_id\0\u{1}state\0\u{3}caller_name\0\u{3}caller_number\0\u{3}caller_photo_png\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.callID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.callerName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.callerNumber) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.callerPhotoPng) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.callID.isEmpty {
      try visitor.visitSingularStringField(value: self.callID, fieldNumber: 1)
    }
    if self.state != .incoming {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 2)
    }
    if !self.callerName.isEmpty {
      try visitor.visitSingularStringField(value: self.callerName, fieldNumber: 3)
    }
    if !self.callerNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.callerNumber, fieldNumber: 4)
    }
    if !self.callerPhotoPng.isEmpty {
      try visitor.visitSingularBytesField(value: self.callerPhotoPng, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLCallEvent, rhs: MLCallEvent) -> Bool {
    if lhs.callID != rhs.callID {return false}
    if lhs.state != rhs.state {return false}
    if lhs.callerName != rhs.callerName {return false}
    if lhs.callerNumber != rhs.callerNumber {return false}
    if lhs.callerPhotoPng != rhs.callerPhotoPng {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLCallEvent.State: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INCOMING\0\u{1}ACCEPTED\0\u{1}REJECTED\0\u{1}ENDED\0\u{1}OUTGOING\0")
}

extension MLAudioOffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioOffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}call_id\0\u{1}sdp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.callID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sdp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.callID.isEmpty {
      try visitor.visitSingularStringField(value: self.callID, fieldNumber: 1)
    }
    if !self.sdp.isEmpty {
      try visitor.visitSingularStringField(value: self.sdp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLAudioOffer, rhs: MLAudioOffer) -> Bool {
    if lhs.callID != rhs.callID {return false}
    if lhs.sdp != rhs.sdp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLAudioAnswer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioAnswer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}call_id\0\u{1}sdp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.callID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sdp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.callID.isEmpty {
      try visitor.visitSingularStringField(value: self.callID, fieldNumber: 1)
    }
    if !self.sdp.isEmpty {
      try visitor.visitSingularStringField(value: self.sdp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLAudioAnswer, rhs: MLAudioAnswer) -> Bool {
    if lhs.callID != rhs.callID {return false}
    if lhs.sdp != rhs.sdp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLIceCandidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IceCandidate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}call_id\0\u{1}candidate\0\u{3}sdp_mid\0\u{3}sdp_mline_index\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.callID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.candidate) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sdpMid) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.sdpMlineIndex) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.callID.isEmpty {
      try visitor.visitSingularStringField(value: self.callID, fieldNumber: 1)
    }
    if !self.candidate.isEmpty {
      try visitor.visitSingularStringField(value: self.candidate, fieldNumber: 2)
    }
    if !self.sdpMid.isEmpty {
      try visitor.visitSingularStringField(value: self.sdpMid, fieldNumber: 3)
    }
    if self.sdpMlineIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.sdpMlineIndex, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLIceCandidate, rhs: MLIceCandidate) -> Bool {
    if lhs.callID != rhs.callID {return false}
    if lhs.candidate != rhs.candidate {return false}
    if lhs.sdpMid != rhs.sdpMid {return false}
    if lhs.sdpMlineIndex != rhs.sdpMlineIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MLHeartbeat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Heartbeat"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sent_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.sentAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sentAt != 0 {
      try visitor.visitSingularInt64Field(value: self.sentAt, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: MLHeartbeat, rhs: MLHeartbeat) -> Bool {
    if lhs.sentAt != rhs.sentAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
